"""Create the tables of db repetiteur

Revision ID: 34c8066a4f8a
Revises: 
Create Date: 2024-11-29 06:04:50.692808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c8066a4f8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('date_modify', sa.Integer(), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('modify_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['features.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_features_timestamp'), ['timestamp'], unique=False)

    op.create_table('parents',
    sa.Column('nomcomplet_parent', sa.String(length=30), nullable=True),
    sa.Column('telephone', sa.String(length=10), nullable=True),
    sa.Column('lieu', sa.String(length=25), nullable=True),
    sa.Column('quartHab', sa.String(length=25), nullable=True),
    sa.Column('password_hash', sa.String(length=250), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('date_modify', sa.Integer(), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('modify_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repetiteurs',
    sa.Column('nomcomplet', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('contactWhats', sa.String(length=10), nullable=True),
    sa.Column('lieu', sa.String(length=25), nullable=True),
    sa.Column('quartHab', sa.String(length=25), nullable=True),
    sa.Column('classPrim', sa.String(length=100), nullable=True),
    sa.Column('classSecond', sa.String(length=150), nullable=True),
    sa.Column('annExp', sa.String(length=2), nullable=True),
    sa.Column('nivEtud', sa.String(length=10), nullable=True),
    sa.Column('passwordR', sa.String(length=250), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('date_modify', sa.Integer(), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('modify_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repetiteurs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repetiteurs_email'), ['email'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=56), nullable=False),
    sa.Column('last_name', sa.String(length=56), nullable=False),
    sa.Column('telephone', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('password_hash', sa.String(length=250), nullable=True),
    sa.Column('date_pwd_generated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_telephone'), ['telephone'], unique=True)

    op.create_table('user_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('date_modify', sa.Integer(), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('modify_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_type_timestamp'), ['timestamp'], unique=False)

    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('user_type_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('date_modify', sa.Integer(), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('modify_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_timestamp'))

    op.drop_table('rules')
    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_type_timestamp'))

    op.drop_table('user_type')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_telephone'))
        batch_op.drop_index(batch_op.f('ix_user_phone'))

    op.drop_table('user')
    with op.batch_alter_table('repetiteurs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repetiteurs_email'))

    op.drop_table('repetiteurs')
    op.drop_table('parents')
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_features_timestamp'))

    op.drop_table('features')
    # ### end Alembic commands ###
